const Joi = require('joi');

const createEmployeeSchema = Joi.object({
  customerId: Joi.string().optional(),
  firstName: Joi.string().required(),
  lastName: Joi.string().required(),
  middleName: Joi.string().optional(),
  email: Joi.string().email().required(),
  knownAsFirstName: Joi.string().optional(),
  knownAsLastName: Joi.string().optional(),
  employeeId: Joi.string().optional(),
  employeePin: Joi.string().optional(),
  employeeRefNumber: Joi.string().optional(),
  mobileNumber: Joi.string().optional(),
  accessPrivilege: Joi.string().valid('Super Admin', 'Admin', 'Manager', 'Employee').optional(),
  subContractor: Joi.string().optional(),
  employmentType: Joi.string().valid('Full-time', 'Part-time', 'Contractor', 'Intern').optional(),
  startDate: Joi.date().optional(),
  endDate: Joi.date().optional(),
  conditionalFrom: Joi.date().optional(),
  confirmFrom: Joi.date().optional(),
  dob: Joi.date().optional(),
  title: Joi.string().optional(),
  fullNameAtBirth: Joi.string().optional(),
  motherName: Joi.string().optional(),
  placeOfBirth: Joi.string().optional(),
  countryOfBirth: Joi.string().optional(),
  noticeDate: Joi.date().optional(),
  leavingDate: Joi.date().optional(),
  status: Joi.string().valid('Active', 'Deactive').optional(),
});

const updateEmployeeSchema = Joi.object({
  customerId: Joi.string().optional(),
  firstName: Joi.string().optional(),
  lastName: Joi.string().optional(),
  middleName: Joi.string().optional(),
  email: Joi.string().email().optional(),
  knownAsFirstName: Joi.string().optional(),
  knownAsLastName: Joi.string().optional(),
  employeeId: Joi.string().optional(),
  employeePin: Joi.string().optional(),
  employeeRefNumber: Joi.string().optional(),
  mobileNumber: Joi.string().optional(),
  accessPrivilege: Joi.string().valid('Super Admin', 'Admin', 'Manager', 'Employee').optional(),
  subContractor: Joi.string().optional(),
  employmentType: Joi.string().valid('Full-time', 'Part-time', 'Contractor', 'Intern').optional(),
  startDate: Joi.date().optional(),
  endDate: Joi.date().optional(),
  conditionalFrom: Joi.date().optional(),
  confirmFrom: Joi.date().optional(),
  dob: Joi.date().optional(),
  title: Joi.string().optional(),
  fullNameAtBirth: Joi.string().optional(),
  motherName: Joi.string().optional(),
  placeOfBirth: Joi.string().optional(),
  countryOfBirth: Joi.string().optional(),
  noticeDate: Joi.date().optional(),
  leavingDate: Joi.date().optional(),
  status: Joi.string().valid('Active', 'Deactive').optional(),
}).min(1);

module.exports = { createEmployeeSchema, updateEmployeeSchema };
